[package]
name = "planter-core"
version = "0.0.4"
edition = "2024"
authors = ["Sebastiano Giordano"]
description = "Domain logic for PlanTer, a project management application"
documentation = "https://docs.rs/planter-core"
keywords = ["project_management"]
license = "AGPL-3.0-or-later"
readme = "README.md"
repository = "https://github.com/krahos/planter-core"

[lib]
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.102"
chrono = "0.4.45"
uuid = { version = "1", features = ["v4"] }
phonenumber = "0.3.9"
regex = "1.12.4"
thiserror = "2.0.18"
nutype = "0.7.0"
email_address = "0.2.9"
bon = "3.9.3"

[dev-dependencies]
proptest = { version = "1.11.0", features = ["proptest-macro"] }
rand = "0.10.1"

[lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"
